### ISSUE TITLE
General base classes for workflows

### ISSUE THREAD

**Issue by JosePizarro3** [nomad-coe/nomad-schema-plugin-simulation-workflow#2]
@ladinesa I think we could transfer some quantities with references to the typical properties as base classes that then the workflows can inherit.

To put an example, take the GW and the DMFT workflows. Both `GWResults` and `DMFTResults` share DFT properties, hence I suggest creating `DFTOutputs(SimulationWorkflowResults)` (and `GWOutputs`, `DMFTOutputs`, etc) and use inheritance `GWResults(DFTOutputs, GWOutputs)`.

We can also rework the `normalization()` of this cases in a more oop way. 

What do you think? Do you want to tackle it or do you want me to do it?

**Comment by ladinesa** [comment]
I think this is a similar case e.g to ThermodynamicsResults which is subclassed by MolecularDynamicsResults. You may have to take note of the order by which the normalize functions are executed. That is why i recently implemented normalization_level to ArchiveSection. I think you are more familiar with the schema so it would be best if you take care of it.
